-- MySQL Script generated by MySQL Workbench
-- Thu Aug  6 17:28:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`profil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profil` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nama_lengkap` VARCHAR(100) NULL,
  `email` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jawaban`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`jawaban` ;

CREATE TABLE IF NOT EXISTS `mydb`.`jawaban` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isi` VARCHAR(255) NULL,
  `tanggal_dibuat` DATE NULL,
  `tanggal_diperbaharui` DATE NULL,
  `pertanyaan_id` INT NOT NULL,
  `profil_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jawaban_pertanyaan_idx` (`pertanyaan_id` ASC) VISIBLE,
  INDEX `fk_jawaban_profil1_idx` (`profil_id` ASC) VISIBLE,
  CONSTRAINT `fk_jawaban_pertanyaan`
    FOREIGN KEY (`pertanyaan_id`)
    REFERENCES `mydb`.`pertanyaan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jawaban_profil1`
    FOREIGN KEY (`profil_id`)
    REFERENCES `mydb`.`profil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pertanyaan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pertanyaan` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pertanyaan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `judul` VARCHAR(45) NULL,
  `isi` VARCHAR(255) NULL,
  `tanggal_dibuat` DATE NULL,
  `tanggal_diperbaharui` DATE NULL,
  `jawaban_tepat_id` INT NOT NULL,
  `profil_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pertanyaan_jawaban1_idx` (`jawaban_tepat_id` ASC) VISIBLE,
  INDEX `fk_pertanyaan_profil1_idx` (`profil_id` ASC) VISIBLE,
  CONSTRAINT `fk_pertanyaan_jawaban1`
    FOREIGN KEY (`jawaban_tepat_id`)
    REFERENCES `mydb`.`jawaban` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pertanyaan_profil1`
    FOREIGN KEY (`profil_id`)
    REFERENCES `mydb`.`profil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`komentar_pertanyaan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`komentar_pertanyaan` ;

CREATE TABLE IF NOT EXISTS `mydb`.`komentar_pertanyaan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isi` VARCHAR(255) NULL,
  `tanggal_dibuat` DATE NULL,
  `pertanyaan_id` INT NOT NULL,
  `profil_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_komentar_pertanyaan_pertanyaan1_idx` (`pertanyaan_id` ASC) VISIBLE,
  INDEX `fk_komentar_pertanyaan_profil1_idx` (`profil_id` ASC) VISIBLE,
  CONSTRAINT `fk_komentar_pertanyaan_pertanyaan1`
    FOREIGN KEY (`pertanyaan_id`)
    REFERENCES `mydb`.`pertanyaan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_komentar_pertanyaan_profil1`
    FOREIGN KEY (`profil_id`)
    REFERENCES `mydb`.`profil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`komentar_jawaban`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`komentar_jawaban` ;

CREATE TABLE IF NOT EXISTS `mydb`.`komentar_jawaban` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isi` VARCHAR(255) NULL,
  `tanggal_dibuat` DATE NULL,
  `jawaban_id` INT NOT NULL,
  `profil_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_komentar_jawaban_jawaban1_idx` (`jawaban_id` ASC) VISIBLE,
  INDEX `fk_komentar_jawaban_profil1_idx` (`profil_id` ASC) VISIBLE,
  CONSTRAINT `fk_komentar_jawaban_jawaban1`
    FOREIGN KEY (`jawaban_id`)
    REFERENCES `mydb`.`jawaban` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_komentar_jawaban_profil1`
    FOREIGN KEY (`profil_id`)
    REFERENCES `mydb`.`profil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`like_dislike_pertanyaan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`like_dislike_pertanyaan` ;

CREATE TABLE IF NOT EXISTS `mydb`.`like_dislike_pertanyaan` (
  `pertanyaan_id` INT NOT NULL,
  `profil_id` INT NOT NULL,
  `poin` INT(11) NULL,
  PRIMARY KEY (`pertanyaan_id`, `profil_id`),
  INDEX `fk_pertanyaan_has_profil_profil1_idx` (`profil_id` ASC) VISIBLE,
  INDEX `fk_pertanyaan_has_profil_pertanyaan1_idx` (`pertanyaan_id` ASC) VISIBLE,
  CONSTRAINT `fk_pertanyaan_has_profil_pertanyaan1`
    FOREIGN KEY (`pertanyaan_id`)
    REFERENCES `mydb`.`pertanyaan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pertanyaan_has_profil_profil1`
    FOREIGN KEY (`profil_id`)
    REFERENCES `mydb`.`profil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`like_dislike_jawaban`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`like_dislike_jawaban` ;

CREATE TABLE IF NOT EXISTS `mydb`.`like_dislike_jawaban` (
  `jawaban_id` INT NOT NULL,
  `profil_id` INT NOT NULL,
  `poin` INT(11) NULL,
  PRIMARY KEY (`jawaban_id`, `profil_id`),
  INDEX `fk_jawaban_has_profil_profil1_idx` (`profil_id` ASC) VISIBLE,
  INDEX `fk_jawaban_has_profil_jawaban1_idx` (`jawaban_id` ASC) VISIBLE,
  CONSTRAINT `fk_jawaban_has_profil_jawaban1`
    FOREIGN KEY (`jawaban_id`)
    REFERENCES `mydb`.`jawaban` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jawaban_has_profil_profil1`
    FOREIGN KEY (`profil_id`)
    REFERENCES `mydb`.`profil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
